import type { SocialLink } from "@/config/types";

export const socialSectionConfig = {
  title: "Elsewhere",
};

export const socialsConfig: SocialLink[] = [
  {
    id: "github",
    platform: "GitHub",
    handle: "@AdityaKodez",
    href: "https://github.com/AdityaKodez",
    icon: "github",
    action: "external",
    order: 1,
    enabled: true,
  },
  {
    id: "x",
    platform: "X (Twitter)",
    handle: "@AdiKodez",
    href: "https://x.com/AdiKodez",
    icon: "x",
    action: "external",
    tooltipDefault: "Message on X",
    order: 2,
    enabled: true,
  },
  {
    id: "peerlist",
    platform: "Peerlist",
    handle: "@faker",
    href: "https://peerlist.io/faker",
    icon: "peerlist",
    action: "external",
    order: 3,
    enabled: true,
  },
  {
    id: "discord",
    platform: "Discord",
    handle: "@t1x_faker",
    icon: "discord",
    action: "copy",
    copyValue: "t1x_faker",
    shortcutKey: "C",
    tooltipDefault: "Copy username",
    order: 4,
    enabled: true,
  },
  {
    id: "email",
    platform: "Email",
    handle: "adityakodez@gmail.com",
    href: "mailto:adityakodez@gmail.com",
    icon: "gmail",
    action: "mailto",
    tooltipDefault: "Send email",
    order: 5,
    enabled: true,
  },
  {
    id: "reddit",
    platform: "Reddit",
    handle: "u/Affectionate-Gur-318",
    href: "https://www.reddit.com/user/Affectionate-Gur-318/",
    icon: "reddit",
    action: "external",
    tooltipDefault: "Visit Reddit profile",
    order: 6,
    enabled: true,
  },
];
