import type { SocialLink } from "@/config/types";

export const socialSectionConfig = {
  title: "Connect",
};

export const socialsConfig: SocialLink[] = [
  {
    id: "github",
    platform: "GitHub",
    handle: "@AdityaKodez",
    href: "https://github.com/AdityaKodez",
    icon: "github",
    action: "external",
    order: 1,
    enabled: true,
  },
  {
    id: "x",
    platform: "X (Twitter)",
    handle: "@AdiKodez",
    href: "https://x.com/AdiKodez",
    icon: "x",
    action: "external",
    order: 2,
    enabled: true,
  },
  {
    id: "peerlist",
    platform: "Peerlist",
    handle: "@faker",
    href: "https://peerlist.io/faker",
    icon: "peerlist",
    action: "external",
    order: 3,
    enabled: true,
  },
  {
    id: "discord",
    platform: "Discord",
    handle: "@t1x_faker",
    icon: "discord",
    action: "copy",
    copyValue: "t1x_faker",
    shortcutKey: "C",
    tooltipDefault: "Click to copy",
    order: 4,
    enabled: true,
  },
  {
    id: "email",
    platform: "Email",
    handle: "adityakodez@gmail.com",
    href: "mailto:adityakodez@gmail.com",
    icon: "gmail",
    action: "copy",
    copyValue: "adityakodez@gmail.com",
    shortcutKey: "E",
    tooltipDefault: "Click to copy",
    order: 5,
    enabled: true,
  },
  {
    id: "coffee",
    platform: "Buy me a coffee",
    handle: "@adiKodez",
    href: "https://buymeacoffee.com/adiKodez",
    icon: "coffee",
    action: "external",
    tooltipDefault: "Thank You ❤️",
    order: 6,
    enabled: true,
  },
];
