import type { Testimonial } from "@/config/types";

export const testimonialsConfig: Testimonial[] = [
  {
    id: "parth",
    name: "Parth",
    role: "@mittalparth_ on X",
    content:
      "==neat!== ==footer pretty nice!== ~can add more logos and icons for the experience / work section in my opinion~",
    avatar: "PM",
    image: "/testimonial/parth.webp",
    order: 1,
    enabled: true,
  },
  {
    id: "siddharth",
    name: "Siddharth",
    role: "@buildwithsid on X",
    content:
      "==really cool==, i like the ==gta 5 map thing at the top==, and ==overall aesthetic is really nice aswell==",
    avatar: "SI",
    image: "/testimonial/siddharth.webp",
    order: 2,
    enabled: true,
  },
  {
    id: "sahil",
    name: "Sahil",
    role: "@sahill_og on X",
    content: "Cool bro",
    avatar: "SA",
    image: "/testimonial/sahil.webp",
    order: 3,
    enabled: true,
  },
  {
    id: "nikhil",
    name: "nikhil · sys/quests",
    role: "@nick_realm_01 on X",
    content: "Sexyy bhai🔥🔥",
    avatar: "NK",
    image: "/testimonial/nikhil.webp",
    order: 4,
    enabled: true,
  },
  {
    id: "natey",
    name: "natey_mac",
    role: "Redditor",
    content:
      "This is great. Most of the portfolios people post here are doing WAY too much. Yours here shows off just enough skill and an eye for design and doesn’t look like a boiler plate template to me at least. So great work. No notes.",
    avatar: "NM",
    image: "/testimonial/natey.webp",
    order: 5,
    enabled: true,
  },
  {
    id: "elongated",
    name: "ElongatedBear",
    role: "Redditor",
    content: "You've got a good eye for design",
    avatar: "EB",
    image: "/testimonial/elongated.webp",
    order: 6,
    enabled: true,
  },
  {
    id: "garvit",
    name: "Garvit Joshi",
    role: "Creator of animbits.dev.",
    content: "I like the minimalistic look good work.",
    avatar: "GJ",
    image: "/testimonial/garvit.webp",
    order: 7,
    enabled: true,
  },
  {
    id: "vishal",
    name: "Vishal Sharma",
    role: "Student",
    content:
      "Your portfolio UI looks good, well which tech stack and state management you have used ?",
    avatar: "VS",
    image: "/testimonial/vishal.webp",
    order: 8,
    enabled: false,
  },
  {
    id: "vivek",
    name: "Vivek Singh",
    role: "CoFounder at Digia",
    content: "Congrats on your launch. Looking forward",
    avatar: "VS",
    image: "/testimonial/vivek.webp",
    order: 9,
    enabled: false,
  },
  {
    id: "Tolani",
    name: "Tolani",
    role: "Frontend Developer",
    content: "Just took a look And i love it",
    avatar: "TL",
    image: "/testimonial/tolani.webp",
    order: 10,
    enabled: false,
  },
];
