import type { Testimonial } from "@/config/types";

export const testimonialsSectionConfig = {
  seeMoreLabel: "view all",
};

export const testimonialsConfig: Testimonial[] = [
  {
    id: "natey",
    name: "natey_mac",
    role: "Redditor",
    content:
      "This is great. Most of the portfolios people post here are doing WAY too much. Yours here shows off just enough skill and an eye for design and doesn’t look like a boiler plate template to me at least. So great work. No notes.",
    avatar: "NM",
    image: "/testimonial/natey.png",
    order: 1,
    enabled: true,
  },
  {
    id: "elongated",
    name: "ElongatedBear",
    role: "Redditor",
    content: "You've got a good eye for design",
    avatar: "EB",
    image: "/testimonial/elongated.png",
    order: 2,
    enabled: true,
  },
  {
    id: "garvit",
    name: "Garvit Joshi",
    role: "Creator of animbits.dev.",
    content: "I like the minimalistic look good work.",
    avatar: "GJ",
    image: "/testimonial/garvit.png",
    order: 3,
    enabled: true,
  },
  {
    id: "kraig",
    name: "KraiG",
    role: "Creative Designer",
    content:
      "Thanks! Lovely, what more can I say just build and build and build...",
    avatar: "KG",
    image: "/testimonial/kraig.jpg",
    href: "https://x.com/kraigdesigns/status/2096635026301653129",
    order: 4,
    enabled: true,
  },
  {
    id: "quby",
    name: "Quby",
    role: "Design Engineer",
    content: "Very nice man",
    avatar: "QB",
    image: "/testimonial/quby.jpg",
    href: "https://x.com/qubydev/status/2096923486472282565",
    order: 5,
    enabled: true,
  },
  {
    id: "rachit",
    name: "Rachit Thakur",
    role: "Designer & Builder",
    content: "Looks cool bro",
    avatar: "RT",
    image: "/testimonial/rachit.jpg",
    href: "https://x.com/RachitThakur146/status/2096605817797828840",
    order: 6,
    enabled: true,
  },
  {
    id: "rohit",
    name: "Rohit",
    role: "Developer",
    content: "Love the minimal vibe. Cool",
    avatar: "RH",
    image: "/testimonial/rohit.jpg",
    href: "https://x.com/turquoise_0904/status/2096624805302980644",
    order: 7,
    enabled: true,
  },
  {
    id: "gaurav",
    name: "gauravii",
    role: "Agency Builder",
    content: "That looks good!",
    avatar: "GV",
    image: "/testimonial/gaurav.jpg",
    href: "https://x.com/gauraavvii/status/2094417132327170276",
    order: 8,
    enabled: true,
  },
  {
    id: "vishal",
    name: "Vishal Sharma",
    role: "Student",
    content:
      "Your portfolio UI looks good, well which tech stack and state management you have used ?",
    avatar: "VS",
    image: "/testimonial/vishal.png",
    order: 9,
    enabled: false,
  },
  {
    id: "vivek",
    name: "Vivek Singh",
    role: "CoFounder at Digia",
    content: "Congrats on your launch. Looking forward",
    avatar: "VS",
    image: "/testimonial/vivek.png",
    order: 10,
    enabled: false,
  },
  {
    id: "Tolani",
    name: "Tolani",
    role: "Frontend Developer",
    content: "Just took a look And i love it",
    avatar: "TL",
    image: "/testimonial/tolani.png",
    order: 11,
    enabled: false,
  },
  {
    id: "Sahil",
    name: "Sahil Sahu",
    role: "Developer",
    content: "Cool bro",
    avatar: "SA",
    image: "/testimonial/sahil.png",
    order: 12,
    enabled: false,
  },
  {
    id: "kiyotaka",
    name: "kiyota",
    role: "Building @oxygenui",
    content: "Thx, urs also look minimal with creative touch cool.",
    avatar: "KI",
    image: "/testimonial/kiyotaka.jpg",
    href: "https://x.com/SubhanHQ/status/2097214653839655168",
    order: 13,
    enabled: true,
  },
  {
    id: "arindam",
    name: "arindam",
    role: "founder @studio1hq",
    content: "nice asthetics. liked the cute 'ask the ai' button.",
    avatar: "AM",
    image: "/testimonial/arindam.jpg",
    href: "https://x.com/Arindam_1729/status/2097226574190055793",
    order: 14,
    enabled: true,
  },
  {
    id: "ionleu",
    name: "John",
    role: "@ionleu",
    content: "love it! I may get inspired 😅🔥",
    avatar: "JO",
    image: "/testimonial/john.jpg",
    href: "https://x.com/ionleu/status/2099212395033850082",
    order: 15,
    enabled: true,
  },
  {
    id: "rakibulism",
    name: "Rakibul",
    role: "Design Engineer",
    content: "love the dark with simplicity !",
    avatar: "RK",
    image: "/testimonial/rakibul.jpg",
    href: "https://x.com/rakibulism/status/2099197714840121427",
    order: 16,
    enabled: true,
  },
  {
    id: "whysoraj",
    name: "Raj",
    role: "@whysoraj",
    content: "This is so clean and crisp.",
    avatar: "RJ",
    image: "/testimonial/raj.jpg",
    href: "https://x.com/whysoraj/status/2099416403501842665",
    order: 17,
    enabled: true,
  },
  {
    id: "bhushan",
    name: "Bhushan",
    role: "Programmer",
    content: "cool website man .",
    avatar: "BH",
    image: "/testimonial/bhushan.jpg",
    href: "https://x.com/Bhushan4work_/status/2099394338291843340",
    order: 18,
    enabled: true,
  },
  {
    id: "owais",
    name: "Muhammad Owais Warsi",
    role: "writing and shipping softwares",
    content:
      "Thanks, I have already checked your portfolio several times even before this comment...amazing",
    avatar: "MO",
    image: "/testimonial/owais.jpg",
    href: "https://x.com/MO_warsi786/status/2100838324084826595",
    order: 19,
    enabled: true,
  },
];

/** Every testimonial in authored order. Used by the /testimonials page. */
export function getAllTestimonials(): Testimonial[] {
  return [...testimonialsConfig].sort((a, b) => a.order - b.order);
}

/** Only the published ones. Used by the home page marquee. */
export function getEnabledTestimonials(): Testimonial[] {
  return getAllTestimonials().filter((item) => item.enabled !== false);
}
